CREATE TABLE `markets` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `city_id` bigint unsigned NOT NULL,
  `region_id` bigint unsigned NOT NULL,
  `market_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `market_slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `market_thumbnail` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `market_address` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `market_phone` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `market_wa` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `market_lat` decimal(11,7) DEFAULT NULL,
  `market_long` decimal(11,7) DEFAULT NULL,
  `market_gmap` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `markets_market_slug_unique` (`market_slug`),
  KEY `markets_city_id_foreign` (`city_id`),
  KEY `markets_region_id_foreign` (`region_id`),
  CONSTRAINT `markets_city_id_foreign` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE CASCADE,
  CONSTRAINT `markets_region_id_foreign` FOREIGN KEY (`region_id`) REFERENCES `regions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
