CREATE TABLE `rentals` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `city_id` bigint unsigned NOT NULL,
  `region_id` bigint unsigned NOT NULL,
  `market_id` bigint unsigned NOT NULL,
  `rental_name` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rental_slug` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rental_address` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rental_cover` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rental_desc` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rental_phone` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rental_wa` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rental_price` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rental_posisi` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rental_size` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rental_iframe` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rental_gmap` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_recommended` tinyint(1) NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `rentals_city_id_foreign` (`city_id`),
  KEY `rentals_region_id_foreign` (`region_id`),
  KEY `rentals_market_id_foreign` (`market_id`),
  CONSTRAINT `rentals_city_id_foreign` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE CASCADE,
  CONSTRAINT `rentals_market_id_foreign` FOREIGN KEY (`market_id`) REFERENCES `markets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `rentals_region_id_foreign` FOREIGN KEY (`region_id`) REFERENCES `regions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
