CREATE TABLE `stalls` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `city_id` bigint unsigned NOT NULL,
  `region_id` bigint unsigned NOT NULL,
  `market_id` bigint unsigned NOT NULL,
  `stall_name` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `stall_slug` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `stall_address` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `stall_cover` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stall_desc` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `stall_operational` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `stall_phone` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL,
  `stall_wa` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL,
  `stall_iframe` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `stall_gmap` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `stalls_city_id_foreign` (`city_id`),
  KEY `stalls_region_id_foreign` (`region_id`),
  KEY `stalls_market_id_foreign` (`market_id`),
  CONSTRAINT `stalls_city_id_foreign` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE CASCADE,
  CONSTRAINT `stalls_market_id_foreign` FOREIGN KEY (`market_id`) REFERENCES `markets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `stalls_region_id_foreign` FOREIGN KEY (`region_id`) REFERENCES `regions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
